# This is a basic workflow to help you get started with Actions

name: Build Android project

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: 
     - master
     - 'android/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testing:
    name: Lint check and Testing
    runs-on: [ubuntu-latest]
    steps:
      - name: Clone Repo
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo #FIREBASE_CONFIG > app/google-services.json
        
      - name: Run linter
        run: ./android/gradlew lintStagingDebugCheck
        
      - name: Run Unit Tests
        run: ./android/gradlew testStagingDebugUnitTest
        
      - name: Assemble Debug Apk
        run: ./android/gradlew assembleStagingDebug
        
      - name: Assemble Debug Test Apk
        run: ./android/gradlew assembleStagingDebugAndroidTest

# TODO: Add Firebase Test Lab to workflow (ticket: )
#      - name: Run Firebase Test Lab tests
#        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
#        with:
#          arg-spec: '${{  }}'
#        env:
#          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
