name: Build Spring app with Maven

on:
  push:
    branches: [ master ]
    paths:
      - "backend/**"
  pull_request:
    branches: 
        - master
        - 'backend/**'
    paths:
      - "backend/**"

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        env:
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          #FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        with:
          java-version: ${{ matrix.java }}
      - run: |
          echo "home: ${{ HOME }}"
          echo "workspace: ${{ GITHUB_WORKSPACE }}"
          mvn -f backend/pom.xml clean compile

  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build Maven project
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build Spring project
      run: mvn -f backend/pom.xml clean verify
    - name: Run tests
      run: mvn -f backend/pom.xml test
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v1
      with:
       name: artifact
       path: backend/target/app-0.0.1-SNAPSHOT.jar
