name: Build Spring app with Maven

on:
  push:
    branches: [ master ]
    paths:
      - "backend/**"
  pull_request:
    branches: 
        - master
        - 'backend/**'
    paths:
      - "backend/**"

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]
    name: Java ${{ matrix.java }} compile
    env:
      working_directory: ./backend
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        env:
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PRIVATE_KEY: ${{ env.working_directory }}/secrets/google.json
        with:
          java-version: ${{ matrix.java }}
      - name: Test pathing
        run: |
          echo Working directory = ${{ env.working_directory }}
        working-directory: ${{env.working_directory}}
      - name: Compile project
        run: mvn clean compile
        working-directory: ${{env.working_directory}}

  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build Maven project
    env:
      working_directory: ./backend
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build Spring project
      run: mvn clean verify
      working-directory: ${{ env.working_directory }}
    - name: Run tests
      run: mvn test
      working-directory: ${{ env.working_directory }}
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v1
      with:
       name: artifact
       path: ${{env.working_directory}}/target/app-0.0.1-SNAPSHOT.jar
